- name: "Install '{{ package_name }}' package using {{ aur_helper }} aur-helper"
  aur:
    name: "{{ package_name }}"
    use: "{{ aur_helper }}"
    state: present
  become: true
  become_user: aur_builder

