roles:
  - src: https://github.com/digimokan/ans_role_add_user
    tags:
      - never
  - src: https://github.com/digimokan/ans_role_config_sudo
    tags:
      - never

collections:
  - name: kewlfft.aur

