- name: "Add dedicated aur-user '{{ aur_user_name }}'"
  ansible.builtin.include_role:
    name: ext/ans_role_add_user
  vars:
    user_name: "{{ aur_user_name }}"
    is_system_user: true
    set_initial_user_password: false

- name: "Configure sudo settings for aur-user '{{ aur_user_name }}'"
  ansible.builtin.include_role:
    name: ext/ans_role_config_sudo
  vars:
    set_auth_for_user: "{{ aur_user_name }}"
    auth_cmd_list:
      - "/usr/bin/pacman"
    req_sudo_password: false

- name: "Install base-devel package, for aur package-building"
  community.general.pacman:
    name: base-devel
    state: present
    # NOTE: ArchWiki recommends the 'needed' flag:
    # https://wiki.archlinux.org/index.php/Arch_User_Repository#Prerequisites
    extra_args: --needed
  become: true
  become_user: root

- name: "Use makepkg to install the aur helper: '{{ aur_helper }}'"
  aur:
    name: "{{ aur_helper }}"
    use: makepkg
    state: present
  become: true
  become_user: aur_builder

