- name: "Configure sudo settings for aur-user '{{ aur_user_name }}'"
  ansible.builtin.include_role:
    name: ext/ans_role_config_sudo
  vars:
    set_auth_for_user: "{{ aur_user_name }}"
    auth_cmd_list:
      - "/usr/bin/pacman"
    req_sudo_password: false

- name: "Install package-group 'base-devel', for aur package-building"
  community.general.pacman:
    name: base-devel
    state: present
    # NOTE: ArchWiki recommends the 'needed' flag:
    # https://wiki.archlinux.org/index.php/Arch_User_Repository#Prerequisites
    extra_args: --needed
  become: true
  become_user: root

- name: "Use makepkg to install the aur helper: '{{ aur_helper }}'"
  aur:
    name: "{{ aur_helper }}"
    use: makepkg
    state: present
  become: true
  become_user: aur_builder

- name: "Create '/usr/local/bin/{{ script_name }}.sh' utility script"
  ansible.builtin.template:
    dest: "/usr/local/bin/{{ script_name }}.sh"
    src: "{{ script_name }}.j2"
    owner: 'root'
    group: 'root'
    mode: '755'
    force: yes
  vars:
    script_name: 'do_aur_sysupgrade'
  become: true
  become_user: root

